#!/bin/bash
alias ls='ls --color=auto'
alias dns='dscacheutil -flushcache;sudo killall -HUP mDNSResponder'
alias k='kubectl'
alias xargs='xargs '
alias fix_brackets="printf '\e[?2004l'"
alias minecraft_screenshots=' open "$HOME/Library/Application Support/minecraft/screenshots"'

source_if_exists() {
    if [ -f $1 ]; then
        source $1
    fi
}

# enable * patterns
shopt -s globstar

# any machine specific changes not to be committed
source_if_exists ~/.bash_profile_local

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

export PATH=~/Library/Python/3.9/bin:$PATH
export TERM=xterm-256color
export BASH_SILENCE_DEPRECATION_WARNING=1

export PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\] \$ '

source_if_exists ~/.bashrc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
source_if_exists "$HOME/.cargo/env"

if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

[[ -f ~/.bashrc ]] && . ~/.bashrc # ghcup-env
source_if_exists "$HOME/.cargo/env"
